export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const LOGGED_FAILED = 'LOGGED_FAILED';
export const LOGOUT = 'LOGOUT';
export const ENABLE_OR_DISABLE_BUTTON = 'ENABLE_OR_DISABLE_BUTTON';
